COP-35470 - while-upgrading-from-3.6.1.1.202 The issue was that upgrade to patch4 on ipv6 and dual stack environments was stuck in system maintenance state; and on one of the nodes we would see the error during node boot up that the virtual ip of the cluster is in use somewhere else. The issue was seen intermittently (several upgrades passed without error)
Root Cause:
As part of the fix for the keepalived vulnerability, we changed the keepalived configuration from authentication type PASS (where password was being sent as clear text) to no authentication and also changed the communication protocol to unicast instead of multicast. We cannot use the other option of auth type AH, reason being CoprHD runs in FIPS compliant mode and internally keepalived used MD5 for its message digest and MD5 is not a FIPs compliant algorithm. So we had to remove auth type from our keepalived configuration and change all multicast communication to unicast so that we do not flood the network with vrrp protocol messages.

During an upgrade, the nodes are updated one by one. So when one node has been updated and others are still waiting update, there is one node with the new configuration (unicast and no-auth type) and remaining nodes with old configuration (multicast and auth type as Password). When a node goes for an upgrade (if this node is the MASTER then it lets go of the VIP and the other nodes sees that there is no master and one of the node with the next highest priority transitions to take up the role of a MASTER). The node that got updated, performs a unicast to all its known peer nodes but the other non-upgraded nodes in the cluster do not respond or acknowledge this vrrp message. The reason being the non-upgraded nodes on seeing this message discards it because they are still working with the auth type PASS authentication and the upgraded node sent a message without any auth. So one of the non-upgraded node disregards this message and holds the VIP without releasing it to the node with the highest priority. So during the process of upgrade there is a state where in there are two VIPs. This is a transient state and would have resolved itself as the nodes are updated one by one and keepalived's master election ensures a single master at the end of the process.

However, the Duplicate IP Checker that checks for Node IP and Virtual IP uniqueness during node bootup detects that there are two nodes assuming the Virtual IP; mis-interprets this as something outside the cluster holding the VIP and stops the node from booting up. This causes the upgrade to stall at this point.

Fix: The duplicate Ip checker logic has been changed to pass the IP uniqueness validation if the VIP is held by multiple nodes within the cluster. This allows the node to boot up, the transient state to resolve and a single master remains at the end of the upgrade. The changes ensure that a duplicate VIP can exist in a cluster, provided that the mac-addresses being returned by the VIP belongs to the nodes of the cluster and not outside of a given cluster. If we find a mac-address unknown to the list of mac-addresses of the nodes in the cluster then we flag and fail the duplicate IP check.  The temporary state of 2 VIPs will and does get resolved post upgrade of all the nodes, keepalived ensures that there is only MASTER node at any given point in time.

Upgrade testing done on 3 node and 5 node setups for IPv4, IPv6 and dual stack combinations.
Duplicate IP checks on IPv4, IPv6 and dual stack setups.
Keepalived state transitions incase of Master node going down and viceversa.
Paths tested as below:
P1 -> 3.6.1.4
P2 -> 3.6.1.4
P3 -> 3.6.1.4
3.6.0 GA-> 3.6.1.4
3.5.0 GA-> 3.6.1.4 and
fresh installs of 3.6.1.4

diff --git a/etc/storageos/ipchecktool b/etc/storageos/ipchecktool
--- a/etc/storageos/ipchecktool
+++ b/etc/storageos/ipchecktool
@@ -42,15 +42,15 @@ _fatal() {
 
 _exit() {
     local code=${1:-1} ; shift
-    set +Ex	
+    set +Ex
     echo "$0: Error: $*" >&2
-    exit ${code}	
+    exit ${code}
 }
 
 _error() {
     local keystroke
     local code=${1:-1} ; shift
-    set +Ex	
+    set +Ex
     echo "$0: Error: $*" >&2
     if [ "$STORAGEOS_BUILD_TYPE" == "oss" ]; then
         echo -e "\n\e[1;31m***\n*** ${*}\n***\n*** Press c to continue boot up, or other keys to edit ${OVFENV_FILE} to correct network settings, and exit the shell. Current node will be rebooted.\n***\e[0m"
@@ -66,7 +66,7 @@ _error() {
             /etc/systool --poweroff 
         fi
         exit ${code}
-    fi		
+    fi
 }
 # Get OVF property with the key provided as $1
 _get_ovf_property() {
@@ -232,22 +232,45 @@ _boot_time_ipv4_vip_dup_test() {
     [ -z "$vip_mac_addr" ] && {
         return 0 # This means no one grabed the vip yet
     } || {
+	# Fetch mac addresses of the nodes within this cluster.
+        mac_array=()
+        for (( n=1; n<=${node_count}; n++ )); do
+            [ "${node_num}" = "${n}" ] && continue
+            local ip=$(_get_ovf_property "network_${n}_ipaddr")
+            local mac_addr=$(arping -D -I ${NIC_NAME} -c 2 ${ip} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+            if [ -n ${mac_addr} ]; then
+                mac_array+=($mac_addr)
+            fi
+        done
         # If vip_mac_addr is not null, it means other nodes grabed the vip, we need to check if it's within the cluster
-        local loopflag=false
-        while true; do
-            for (( n=1; n<=${node_count}; n++ )); do
-                [ "${node_num}" = "${n}" ] && continue
-                local ip=$(_get_ovf_property "network_${n}_ipaddr")
-                local mac_addr=$(arping -D -I ${NIC_NAME} -c 2 ${ip} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)  
-                [ -z "${mac_addr}" ] && {
-                    # This node is down, this node might previously have the vip, so we need to update the vip mac address and do another iteration
-                    loopflag=true
-                    vip_mac_addr=$(arping -D -I ${NIC_NAME} -c 2 ${ipv4_vip} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
-                    [ -z "${vip_mac_addr}" ] && return 0 || continue # The current node might grab the vip back or the vip belongs to no one at this point of time
+
+        for (( n=1; n<=${node_count}; n++ )); do
+            [ "${node_num}" = "${n}" ] && continue
+            local ip=$(_get_ovf_property "network_${n}_ipaddr")
+            local mac_addr=$(arping -D -I ${NIC_NAME} -c 2 ${ip} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+            [ -z "${mac_addr}" ] && {
+                # This node is down, this node might previously have the vip, so we need to update the vip mac address and do another iteration
+                loopflag=true
+                vip_mac_addr=$(arping -D -I ${NIC_NAME} -c 2 ${ipv4_vip} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+                [ -z "${vip_mac_addr}" ] && return 0 || {
+                    if [[ ! " ${mac_array[@]} " =~ " ${vip_mac_addr} " ]]; then
+                        # When the program reaches this line, it means the vip is in use out side of this cluster, so fail
+                        return 1
+                    fi
                 }
-                [[ "${vip_mac_addr}" == *"${mac_addr}"* ]] && return # This means another node in the cluster grabbed the vip, means this vip is not used outside of this cluster, use wildcard here because sometimes FF:FF:FF:FF:FF:FF appears in the vipr_mac_addr
-            done
-            [ "${loopflag}" = false ] && break || loopflag=false
+            }
+	    [ ! -z "${vip_mac_addr}" ] && {
+                # iterate through the mac addresses of all nodes of this cluster to verify, if the VIP is taken up by nodes of this cluster only and not by someone else outside of this cluster.
+                while read -r mac_addr_line
+                do
+                    if [[ ! " ${mac_array[@]} " =~ " ${mac_addr_line} " ]]; then
+                        # When the program reaches this line, it means the vip is in use out side of this cluster, so fail
+                        return 1
+                    fi
+                done <<< "$vip_mac_addr"
+                # When the program reaches this line, it means the vip is in use by some node within this cluster - so all is fine.
+                return 0
+            }
         done
         return 1 # When the program reaches this line, it means no nodes grabbed the vip successfully, means the vip is in use out side of the cluster
     }  
@@ -269,22 +292,44 @@ _boot_time_ipv6_vip_dup_test() {
     [ -z "${vip_mac_addr}" ] && {
         return 0 # This means no one grabed the vip yet
     } || {
-        local loopflag=false
-        while true; do
-            for (( n=1; n<=${node_count}; n++ )); do
-                [ "${node_num}" = "${n}" ] && continue
-                local ip=$(_get_ovf_property "network_${n}_ipaddr6")
-                local mac_addr=$(ndisc6 -m -w 1000 $(_get_ipv6_compressed ${ip}) ${NIC_NAME} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
-                [ -z "${mac_addr}" ] && {
-                    # This node is down, this node might previously have the vip, so we need to update the vip mac address and do another iteration
-                    loopflag=true
-                    vip_mac_addr=$(ndisc6 -m -w 1000 $(_get_ipv6_compressed ${ipv6_vip}) ${NIC_NAME} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
-                    [ -z "${vip_mac_addr}" ] && return 0 || continue # The current node might grab the vip back or the vip belongs to no one at this point of time
-                }
-                [[ "${vip_mac_addr}" == "${mac_addr}" ]] && return # This means another node in the cluster grabbed the vip, means this vip is not used outside of this cluster
-            done            
-            [ "${loopflag}" = false ] && break || loopflag=false
+        # Fetch mac addresses of the nodes within this cluster.
+        mac_array=()
+        for (( n=1; n<=${node_count}; n++ )); do
+            [ "${node_num}" = "${n}" ] && continue
+            local ip=$(_get_ovf_property "network_${n}_ipaddr6")
+            local mac_addr=$(ndisc6 -m -w 1000 $(_get_ipv6_compressed ${ip}) ${NIC_NAME} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+            if [ -n ${mac_addr} ]; then
+                mac_array+=($mac_addr)
+            fi
         done
+        for (( n=1; n<=${node_count}; n++ )); do
+            [ "${node_num}" = "${n}" ] && continue
+            local ip=$(_get_ovf_property "network_${n}_ipaddr6")
+            local mac_addr=$(ndisc6 -m -w 1000 $(_get_ipv6_compressed ${ip}) ${NIC_NAME} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+            [ -z "${mac_addr}" ] && {
+                # This node is down, this node might previously have the vip, so we need to update the vip mac address and do another iteration
+                vip_mac_addr=$(ndisc6 -m -w 1000 $(_get_ipv6_compressed ${ipv6_vip}) ${NIC_NAME} | egrep -o '([[:xdigit:]]{2}[:]){5}[[:xdigit:]]{2}' | uniq)
+                [ -z "${vip_mac_addr}" ] && return 0 || {
+                    if [[ ! " ${mac_array[@]} " =~ " ${vip_mac_addr} " ]]; then
+                        # When the program reaches this line, it means the vip is in use out side of this cluster, so fail
+                        return 1
+                    fi
+                }
+            }
+            [ ! -z "${vip_mac_addr}" ] && {
+                # iterate through the mac addresses of all nodes of this cluster to verify, if the VIP is taken up by nodes of this cluster only and not by someone else outside of this cluster.
+                while read -r mac_addr_line
+                do
+                    if [[ ! " ${mac_array[@]} " =~ " ${mac_addr_line} " ]]; then
+                        # When the program reaches this line, it means the vip is in use out side of this cluster, so fail
+                        return 1
+                    fi
+                done <<< "$vip_mac_addr"
+                # When the program reaches this line, it means the vip is in use by some node within this cluster - so all is fine.
+                return 0
+            }
+        done
+
         return 1 # When the program reaches this line, it means no nodes grabbed the vip successfully, means the vip is in use out side of the cluster
     }
 }
@@ -316,11 +361,11 @@ PANIC=false
 case ${#} in
     1)  case ${1} in
             --panic|-p) PANIC=true; _boot_time_ips_check; _check_gateway ;;
-	     *)    _usage
-	    esac ;;
+            *)    _usage
+            esac ;;
     2)  case ${1} in
             --ip)        _check_ip ${2} ;;
-	     *)          _usage
+            *)          _usage
         esac ;;
-    *)  _usage  		
+    *)  _usage
 esac
