Adding fixes to template after testing, adding exceptions in some cases.

diff --git a/controllersvc/src/conf/imageserver/esxi5x_unattended.template b/controllersvc/src/conf/imageserver/esxi5x_unattended.template
--- a/controllersvc/src/conf/imageserver/esxi5x_unattended.template
+++ b/controllersvc/src/conf/imageserver/esxi5x_unattended.template
@@ -1,8 +1,10 @@
 vmaccepteula
-# WJEIV TODO: Steve already fixing ${clear.device} issue where device is null, so first volume is taken.
-# WJEIV TODO: --overwritevmfs should probably be removed for paranoia, too:  "Permit overwriting of vmfs partitions on the specified drives. By default, overwrite vmfs partitions is not allowed."
-clearpart ${clear.device} --overwritevmfs
-install ${install.device} --overwritevmfs
+# WJEIV TODO [DONE]: Steve already fixing ${clear.device} issue where device is null, so first volume is taken.
+# WJEIV TODO [DONE]: --overwritevmfs should probably be removed for paranoia, too:  "Permit overwriting of vmfs partitions on the specified drives. By default, overwrite vmfs partitions is not allowed."
+# WJEIV TODO [DONE]: If our use case is strictly around exporting a boot volume, installing, THEN exporting shared volumes, then maybe we can ensure the host only sees one device in the first place before it does anything.
+# WJEIV TODO [DONE]: This does mean that any attempt to re-use a volume that's already been formatted to vmfs will not be possible, and may require a workaround/cleanup activity.
+clearpart ${clear.device}
+install ${install.device}
 rootpw --iscrypted  ${root.password}
 network --addvmportgroup=0 --bootproto=dhcp  
 reboot
@@ -11,14 +13,19 @@ reboot
 
 %post --interpreter=busybox --ignorefailure=false 
 localcli network firewall set --enabled false
+
+# ensure there is only one volume (the boot volume) visible to this server
+LINECOUNT=`localcli --format-param=show-header=false storage vmfs extent list | wc -l`
+if [ $LINECOUNT != 1 ] ; then
+echo "There are ${LINECOUNT} volumes seen by this host.  ViPR supports only a boot volume exposed to the host during OS installation to ensure data integrity of shared volumes"
+exit 1
+fi
+
+# WJEIV TODO [DONE]: The issue inserted code for ${DATASTORE_SYM_LINK} is that it does NOT guarantee the wwn is datastore1 at all.  And even if it did, it can't guarantee
+# WJEIV TODO [DONE]: that's the first lun booted after the system comes back up.  I added the check above to ensure one and only one volume.
 # if boot uuid was used, this will create sym link
 ${DATASTORE_SYM_LINK}
 cat /var/log/weasel.log  >> /vmfs/volumes/datastore1/osagent.log 2>&1
-
-# WJEIV TODO: There's no guarantee (that I can see) that /vmfs/volumes/datastore1 is the VMFS associated with ${clear.device}
-# Proof, if there are volumes from this or other arrays already exported to these wwns, they will likely be /vmfs/volumes/datastore1 and
-# This script will firstboot off of that datastore's esxi-firstboot.sh, which is not the one we are writing here.
-# At worst the esxi will come up as a different host, at best it will fail because it's a customer's data lun.
 
 echo $(date +"%Y-%m-%d %T") "INFO Executing %post section" >> /vmfs/volumes/datastore1/osagent.log
 # Downloading custom wget
