adding wait for state, adding sanity tests to sanity script.

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -40,11 +40,11 @@ if [ -f $CONFIG_FILE ]; then
     source ${1}
 else
     echo "Configuration file $CONFIG_FILE not found"
-    #Usage
+    Usage
 fi
 
-
-#[ $# -ge 3 ] || Usage
+echo "what's this |$#"
+[ $# -ge 3 ] || Usage
 date
 
 init_env_var()
@@ -105,6 +105,12 @@ elif [ ${SS} = "vdc" ]; then
         echo AUTH=$AUTH
 elif [ ${SS} = "dr" ]; then
         DR_SITE_B_IP=${4:-$DR_SITE_B_IP}
+        if [ -n "${BOURNE_IPV6_MODE}" ]; then
+            AUTH=ipv6
+        else
+            AUTH=ldap
+        fi
+        echo AUTH=$AUTH
 else
 
 	# By default, we're not running quick sanity
@@ -133,7 +139,8 @@ case $SS in
     ;;
 
     *)
-    #Usage
+    echo "failed here"
+    Usage
 esac
 
 # Webstorage parameters taken from the environment if set.
@@ -177,7 +184,8 @@ case $AUTH in
 	HDS_PROVIDER="lglap095.lss.emc.com"
 	HDS_PROVIDER_IP="2620:0:170:2858::95";;
     *)
-    #Usage
+    echo "NO, failed here"
+    Usage
 esac
 
 ethdev=`/sbin/ifconfig | grep Ethernet | head -1 | awk '{print $1}'`
@@ -234,8 +242,6 @@ VDC_TEST_REMOVE_PROJECT=testremove_vdc_project_$$
 #
 DR_SITE_B_NAME=dr_site_B_$$
 DR_SITE_B_DESCRIPTION="site b description"
-DR_SITE_B_USER=root
-DR_SITE_B_PASSWORD=ChangeMe
 
 #
 # Recovery Configuration
@@ -6235,25 +6241,89 @@ monitor_tests()
 
 dr_setup()
 {
-    echo "Running dr setup"
-    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD	
-    echo "Adding new standby into current vipr system"
-    #dr add $DR_SITE_B_NAME "$DR_SITE_B_DESCRIPTION" $DR_SITE_B_IP $DR_SITE_B_USER $DR_SITE_B_PASSWORD 
-    #if [ $? -ne 0 ]; then
-    #    echo "Add vdc B failed."
-    #    exit 1
-    #fi
-    #sleep 30
-    #vdc waitforstablestate 10 600
-    echo "Adding dr done"
+    #setting pipefail option to pipe exit codes
+    set -o pipefail
+
+    DR_SITE_A_IP=$BOURNE_IPADDR
+    security login $SYSADMIN $SYSADMIN_PASSWORD
+    project_setup
+
 }
 
 dr_tests()
 {
-    echo "Running dr tests"
-    test=$(dr list)
-    echo "printing test"
-    echo $test
+    projectid=$(project query $PROJECT)
+    echo "Project id of $PROJECT is $projectid."
+
+    primary_site=$(dr list "Primary Site"|tail -1) || { echo "get dr primary site failed."; echo $primary_site; exit 1; }
+    echo "primary uuid is $primary_site"
+    
+    echo "---ADD STANDBY SITE---"
+    echo "Adding new standby into current vipr system"
+    standby_site=$(dr add $DR_SITE_B_NAME "$DR_SITE_B_DESCRIPTION" $DR_SITE_B_IP $SYSADMIN $SYSADMIN_PASSWORD|tail -1) || { echo "Add dr site failed."; echo $standby_site; exit 1; }
+    echo "Adding dr done"
+    echo "stanby uuid is $standby_site"    
+
+    echo "---GET SITES---"
+    dr list
+
+    echo "---GET SITE $standby_site---"
+    dr get $standby_site
+
+    echo "---VERIFY SITE $standby_site---"
+    name=$(dr get $standby_site name|tail -1)
+    description=$(dr get $standby_site description|tail -1)
+    vip=$(dr get $standby_site vip|tail -1)
+
+    if [ "$vip" != "$DR_SITE_B_IP" ] ; then
+        echo -e "Fail: site vip \"$vip\" isn't equalt to \"$DR_SITE_B_IP\""
+        exit 1
+    fi
+
+    if [ "$name" != "$DR_SITE_B_NAME" ] ; then
+        echo -e "Fail: site name \"$name\" isn't equalt to \"$DR_SITE_B_NAME\""
+        exit 1
+    fi
+
+    if [ "$description" != "$DR_SITE_B_DESCRIPTION" ] ; then
+        echo -e "Fail: site description \"$description\" isn't equalt to \"$DR_SITE_B_DESCRIPTION\""
+        exit 1
+    fi
+
+    
+    echo "---WAIT FOR SYNC $standby_site---"
+    dr waitforstate $standby_site STANDBY_SYNCED 10 600
+    echo "Syncing dr done"
+
+    # verify project
+    echo "---VERIFY PROJECT SYNCED $standby_site---"
+    BOURNE_IPADDR=$DR_SITE_B_IP
+    security login $SYSADMIN $SYSADMIN_PASSWORD
+    project show $projectid
+
+    # login to standby with auth
+    echo "---LOGIN TO STANDBY WITH SYNCED AUTH $standby_site---"
+    BOURNE_IPADDR=$DR_SITE_B_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+
+    # verify sites in standby
+    echo "---VERIFY sites from standby $standby_site---"
+    dr get $standby_site
+    dr get $primary_site
+
+    # delete standby
+    echo "---DELETE STANDBY $standby_site---"
+    BOURNE_IPADDR=$DR_SITE_A_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+    dr delete $standby_site
+
+    # verify deleted
+    echo "---VERIFY STANDBY DELETED $standby_site---"
+    dr list $DR_SITE_B_NAME || echo "standby removed from site list"
+    dr get $standby_site || echo "standby uuid removed from primary"
+
+    #disabling pipefail option to pipe exit codes
+    set +o pipefail
 }
 
 
