added basic sanity test for /site/uuid/details api

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -6960,6 +6960,20 @@ dr_basic_tests()
     echo "---WAIT FOR STABLE $standby_site---"
     dr waitforstable 30 1200
 
+    echo "---VERIFY SITE DETAILS $standby_site---"
+    state=$(dr details $standby_site clusterState|tail -1)
+    latency=$(dr details $standby_site networkLatencyInMs|tail -1)
+
+    if [ "$state" != "STABLE" ] ; then
+        echo -e "Fail: site clusterState \"$state\" isn't equalt to STABLE"
+        exit 1
+    fi
+
+    if (( $(echo "$latency < 0" | bc -l) )) ; then
+        echo -e "Fail: site latency \"$latency\" isn't calculated correctly, should be 0 or greater"
+        exit 1
+    fi
+
     # verify project
     project show $projectid
 
@@ -7120,6 +7134,20 @@ dr_multisite_tests()
     echo "---WAIT FOR STABLE $standby_site_b---"
     dr waitforstable 30 1200
 
+    echo "---VERIFY SITE DETAILS $standby_site_b---"
+    state=$(dr details $standby_site_b clusterState|tail -1)
+    latency=$(dr details $standby_site_b networkLatencyInMs|tail -1)
+
+    if [ "$state" != "STABLE" ] ; then
+        echo -e "Fail: site clusterState \"$state\" isn't equalt to STABLE"
+        exit 1
+    fi
+
+    if (( $(echo "$latency < 0" | bc -l) )) ; then
+        echo -e "Fail: site latency \"$latency\" isn't calculated correctly, should be 0 or greater"
+        exit 1
+    fi
+
     # verify project
     echo "---VERIFY PROJECT SYNCED $standby_site_b---"
     project show $projectid
@@ -7180,6 +7208,20 @@ dr_multisite_tests()
 
     echo "---WAIT FOR STABLE $standby_site_c---"
     dr waitforstable 30 1200
+
+    echo "---VERIFY SITE DETAILS $standby_site_c---"
+    state=$(dr details $standby_site_c clusterState|tail -1)
+    latency=$(dr details $standby_site_c networkLatencyInMs|tail -1)
+
+    if [ "$state" != "STABLE" ] ; then
+        echo -e "Fail: site clusterState \"$state\" isn't equalt to STABLE"
+        exit 1
+    fi
+
+    if (( $(echo "$latency < 0" | bc -l) )) ; then
+        echo -e "Fail: site latency \"$latency\" isn't calculated correctly, should be 0 or greater"
+        exit 1
+    fi
 
     # verify project
     echo "---VERIFY PROJECT SYNCED $standby_site_c---"
