Fix sanity for new failback testing

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -7494,8 +7494,8 @@ dr_basic_tests()
     # failover test part
     echo "Stopping active site $DR_SITE_B_NAME services to prepare for failover test ..."
     stop_vdc_services "$DR_SITE_B_IP"
-    echo "Sleep 400 seconds to wait standby site (VIP: ${DR_SITE_A_IP}) ZK switch to participant"
-    sleep 400
+    echo "Sleep 1m to wait standby site (VIP: ${DR_SITE_A_IP}) ZK switch to participant"
+    sleep 60
     echo "Wait for site ${DR_SITE_A_NAME} to be stable ..."
     BOURNE_IPADDR=$DR_SITE_A_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
@@ -7503,8 +7503,9 @@ dr_basic_tests()
 
     echo "Failover to promote site $DR_SITE_A_NAME as active ..."
     dr failover --ip "${DR_SITE_A_IP}" $active_site
-    echo "Sleep 800 seconds to wait failover ..."
-    sleep 800
+    echo "Sleep 1m to wait failover ..."
+    sleep 60
+    dr waitforstable --ip "${DR_SITE_A_IP}"  10 800
 
     echo "Wait for site ${DR_SITE_A_NAME} to be stable ..."
     BOURNE_IPADDR=$DR_SITE_A_IP
@@ -7517,8 +7518,8 @@ dr_basic_tests()
     # failback test part
     echo "Starting old active site $DR_SITE_B_NAME services ..."
     start_vdc_services "$DR_SITE_B_IP"
-    echo "Sleep 400 seconds to wait old site to become ACTIVE_DEGRADED ..."
-    sleep 600
+    echo "Sleep 1m to wait old site to become ACTIVE_DEGRADED ..."
+    sleep 60
     BOURNE_IPADDR=$DR_SITE_B_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
     dr waitforstable --ip "${DR_SITE_B_IP}" 10 600
@@ -7529,15 +7530,15 @@ dr_basic_tests()
     BOURNE_IPADDR=$DR_SITE_A_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
     dr waitforstable --ip "${DR_SITE_A_IP}" 10 600
-    echo "---READD STANDBY SITE---"
-    echo "Readding site ${DR_SITE_B_NAME} (ACTIVE_DEGRADED) to site ${DR_SITE_A_NAME} (ACTIVE) after failover ..."
-    standby_site=$(dr add $DR_SITE_B_NAME "$DR_SITE_B_DESCRIPTION" "${DR_SITE_B_IP}" $SYSADMIN $SYSADMIN_PASSWORD|tail -1) || { echo "Add dr site failed."; echo $standby_site; exit 1; }
-    echo "Readding done"
-    echo "Readded standby site uuid is $standby_site"
+    echo "---RESUME OLD ACTIVE SITE---"
+    echo "Resuming site ${DR_SITE_B_NAME} (ACTIVE_DEGRADED) to site ${DR_SITE_A_NAME} (ACTIVE) after failover ..."
+    dr resume --ip "${DR_SITE_A_IP}" $standby_site || { echo "resume dr standby site failed."; exit 1; }
+    echo "Resuming done"
+    echo "Resuming site uuid is $standby_site"
 
     BOURNE_IPADDR=$DR_SITE_A_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
-    echo "Wait standby adding done ..."
+    echo "Wait standby resuming done ..."
     dr waitforstate $standby_site STANDBY_SYNCED 30 1200
 
     # NOTE: after switchover and failover (then readd old active), site A is active and site B is standby
@@ -7811,34 +7812,6 @@ dr_multisite_tests()
     dr waitforstable 30 1200
     project show ${projectid_new}
 
-    # delete standby
-    echo "---DELETE STANDBY $standby_site_b---"
-    BOURNE_IPADDR=$DR_SITE_A_IP
-    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
-    dr delete $standby_site_b
-
-    echo "---WAIT FOR REMOVED $standby_site_b---should throw exceptions---"
-    dr waitforstate $standby_site_b STANDBY_REMOVING 30 600 -n|| echo "standby removed"
-    echo "Removing dr done"
-
-    # verify deleted
-    echo "---VERIFY STANDBY DELETED $standby_site_b---should throw exceptions---"
-    dr list $DR_SITE_B_NAME || echo "standby removed from site list"
-    dr get $standby_site_b || echo "standby uuid removed from active"
-
-    # verify active still works
-    TESTPROJECT=dr_project_$$
-    echo "---CREATE PROJECT $TESTPROJECT ON ACTIVE $active_site---"
-    project show $TESTPROJECT &> /dev/null && return $?
-    project create $TESTPROJECT --tenant $TENANT
-    test_projectid=$(project query $TESTPROJECT)
-    echo "Project id of $TESTPROJECT is $test_projectid."
-
-    # verify stanby C still syncs
-    BOURNE_IPADDR=$DR_SITE_C_IP
-    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
-    project show $test_projectid
-
     # switchover test part
     echo "---WAIT BOTH ACTIVE AND STANBY TO BE STABLE, READY FOR SWITCHOVER---"
     BOURNE_IPADDR=$DR_SITE_A_IP
@@ -7871,9 +7844,8 @@ dr_multisite_tests()
     echo "Stopping active site $DR_SITE_C_NAME services to prepare for failover test ..."
     stop_vdc_services "$DR_SITE_C_IP"
 
-    echo "Sleep 400 seconds to wait standby ZK switch to participant"
-    sleep 400
-
+    echo "Sleep 1m to wait standby ZK switch to participant"
+    sleep 60
     echo "Wait for stable"
     BOURNE_IPADDR=$DR_SITE_A_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
@@ -7882,8 +7854,8 @@ dr_multisite_tests()
     echo "Failover to promote site $DR_SITE_A_NAME as active"
     dr failover --ip "${DR_SITE_A_IP}" $active_site
 
-    echo "Sleep 800 seconds to wait failover"
-    sleep 800
+    echo "Sleep 1m to wait failover"
+    sleep 60
 
     echo "Wait for stable"
     BOURNE_IPADDR=$DR_SITE_A_IP
@@ -7897,11 +7869,55 @@ dr_multisite_tests()
     echo "Starting old active site $DR_SITE_C_NAME services ..."
     start_vdc_services "$DR_SITE_C_IP"
     echo "Sleep 600 seconds to wait old site to become ACTIVE_DEGRADED ..."
-    sleep 600
+    sleep 60
     BOURNE_IPADDR=$DR_SITE_C_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
     dr waitforstable --ip "${DR_SITE_C_IP}" 10 600
     dr waitforstate $standby_site_c ACTIVE_DEGRADED 30 600 --ip "${DR_SITE_C_IP}"
+
+    # readd ACTIVE_DEGRADED
+    echo "Waiting $DR_SITE_A_NAME to be stable ..."
+    BOURNE_IPADDR=$DR_SITE_A_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+    dr waitforstable --ip "${DR_SITE_A_IP}" 10 600
+    echo "---RESUME OLD ACTIVE SITE---"
+    echo "Resuming site ${DR_SITE_C_NAME} (ACTIVE_DEGRADED) to site ${DR_SITE_A_NAME} (ACTIVE) after failover ..."
+    dr resume --ip "${DR_SITE_A_IP}" $standby_site_c || { echo "resume dr standby site c failed."; exit 1; }
+    echo "Resuming done"
+    echo "Resuming site uuid is $standby_site_c"
+
+    BOURNE_IPADDR=$DR_SITE_A_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+    echo "Wait standby resuming done ..."
+    dr waitforstate $standby_site_c STANDBY_SYNCED 30 1200
+
+    # delete standby
+    echo "---DELETE STANDBY $standby_site_b---"
+    BOURNE_IPADDR=$DR_SITE_A_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+    dr delete $standby_site_b
+
+    echo "---WAIT FOR REMOVED $standby_site_b---should throw exceptions---"
+    dr waitforstate $standby_site_b STANDBY_REMOVING 30 600 -n|| echo "standby removed"
+    echo "Removing dr done"
+
+    # verify deleted
+    echo "---VERIFY STANDBY DELETED $standby_site_b---should throw exceptions---"
+    dr list $DR_SITE_B_NAME || echo "standby removed from site list"
+    dr get $standby_site_b || echo "standby uuid removed from active"
+
+    # verify active still works
+    TESTPROJECT=dr_project_$$
+    echo "---CREATE PROJECT $TESTPROJECT ON ACTIVE $active_site---"
+    project show $TESTPROJECT &> /dev/null && return $?
+    project create $TESTPROJECT --tenant $TENANT
+    test_projectid=$(project query $TESTPROJECT)
+    echo "Project id of $TESTPROJECT is $test_projectid."
+
+    # verify stanby C still syncs
+    BOURNE_IPADDR=$DR_SITE_C_IP
+    security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
+    project show $test_projectid
 
     #disabling pipefail option to pipe exit codes
     set +o pipefail
