Sanity Changes for SRDF Metro.

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -16,7 +16,7 @@ Usage()
 {
     echo 'Usage: sanity <configuration_file> <bourne_ip>|<[bourne_ipv6]> {all | snapvx | isilon | vplex | vplexexport | vplexsnap | vnxblock | ingestblock | vnxblock_flex_varray | netapp | netappc | recoverpoint | xtremio | srdf |
  vnxfile | datadomainfile | vnxfile_flex_varray | vmaxblock | hds | vmaxblock_flex_varray | combined_block | blocksnapshot | blockmirror | full_copy | blockconsistencygroup | init | quick |
- errorhandling | vnxe | security | syssvc | audit | monitor | vdc | catalog | recovery | backuprestore backupserver-uri username password | dr | ipsec} [local|ldap] [<timeslot>] | sanzoning | application'
+ errorhandling | vnxe | security | syssvc | audit | monitor | vdc | catalog | recovery | backuprestore| dr | ipsec} [local|ldap] [<timeslot>] | sanzoning | application'
     echo 'E.g.:  sanity conf/sanity.conf 137.69.169.21 all'
     echo 'E.g.:  sanity ~/.sanity/sanity.conf 137.69.169.21 isilon'
     echo 'Note: IPv6 needs to be square bracket surrounded. E.g.:  sanity [2620:0:170:2842::180] security'
@@ -107,23 +107,6 @@ elif [ ${SS} = "vdc" ]; then
 elif [ ${SS} = "dr" ]; then
         DR_SITE_B_IP=${4}
         DR_SITE_C_IP=${5}
-        if [ -n "${BOURNE_IPV6_MODE}" ]; then
-            AUTH=ipv6
-        else
-            AUTH=ldap
-        fi
-        echo AUTH=$AUTH
-elif [ ${SS} = "backuprestore" ]; then
-        if [[ $# -ne 6 ]]; then
-            echo "Invalid backuprestore parameters."
-            echo "usage: backuprestore backup-server-uri username password"
-            exit 1
-        fi
-        
-        BACKUP_SERVER_URL=$4
-        BACKUP_SERVER_USERNAME=$5
-        BACKUP_SERVER_PASSWORD=$6
-
         if [ -n "${BOURNE_IPV6_MODE}" ]; then
             AUTH=ipv6
         else
@@ -364,6 +347,8 @@ COS_VMAXBLOCK_THIN=cosvmaxb_thin
 COS_VMAXBLOCK_THICK=cosvmaxb_thick
 COS_VMAXBLOCK_SRDF_SOURCE=vpool_srdf_source
 COS_VMAXBLOCK_SRDF_TARGET=vpool_srdf_target
+COS_VMAXBLOCK_V3_SRDF_SOURCE=vpool_v3_srdf_source
+COS_VMAXBLOCK_V3_SRDF_TARGET=vpool_v3_srdf_target
 COS_RP=cos_rp
 COS_RP_BASE=cos_rp_base
 COS_HDS=coshds
@@ -1207,6 +1192,10 @@ srdf_setup_once()
     smisprovider create $SRDF_VMAXA_SMIS_DEV $SRDF_VMAXA_SMIS_IP 5988 $SMIS_USER "$SMIS_PASSWD" false
     smisprovider show $SRDF_VMAXB_SMIS_DEV &> /dev/null && return $?
     smisprovider create $SRDF_VMAXB_SMIS_DEV $SRDF_VMAXB_SMIS_IP 5988 $SMIS_USER "$SMIS_PASSWD" false
+    smisprovider show $SRDF_V3_VMAXA_SMIS_DEV &> /dev/null && return $?
+    smisprovider create $SRDF_V3_VMAXA_SMIS_DEV $SRDF_V3_VMAXA_SMIS_IP 5988 $SMIS_USER "$SMIS_PASSWD" false
+    smisprovider show $SRDF_V3_VMAXB_SMIS_DEV &> /dev/null && return $?
+    smisprovider create $SRDF_V3_VMAXB_SMIS_DEV $SRDF_V3_VMAXB_SMIS_IP 5988 $SMIS_USER "$SMIS_PASSWD" false
 
     # Adding additional array in order to test pool matching.
     # smisprovider show $VMAX_SMIS_DEV &> /dev/null && return $?
@@ -1217,6 +1206,8 @@ srdf_setup_once()
     storagedevice discover_all --ignore_error
     discoveredsystem show $SRDF_VMAXA_NATIVEGUID &> /dev/null && return $?
     discoveredsystem show $SRDF_VMAXB_NATIVEGUID &> /dev/null && return $?
+    discoveredsystem show $SRDF_V3_VMAXA_NATIVEGUID &> /dev/null && return $?
+    discoveredsystem show $SRDF_V3_VMAXB_NATIVEGUID &> /dev/null && return $?
 }
 
 srdf_common_setup() {
@@ -1243,7 +1234,9 @@ srdf_common_setup() {
     run neighborhood allow $NH $TENANT
     run neighborhood allow $NH $TENANT
 
+    srdf_v3_varray_setup
     srdf_cos_setup
+    srdf_v3_cos_setup
 }
 
 srdf_cos_setup()
@@ -1294,7 +1287,58 @@ srdf_cos_setup()
     cos update block ${COS_VMAXBLOCK_SRDF_SOURCE}_async --storage ${SRDF_VMAXA_NATIVEGUID}
     cos update block ${COS_VMAXBLOCK_SRDF_SOURCE}_async --storage ${SRDF_VMAXB_NATIVEGUID}
     cos allow ${COS_VMAXBLOCK_SRDF_SOURCE}_async block $TENANT
+}
 
+srdf_v3_varray_setup()
+{
+    echo '*** SRDF V3 varray setup ***'
+
+    # Create Virtual Array
+    run neighborhood create $V3_SRDF_VARRAY
+    run neighborhood allow $V3_SRDF_VARRAY $TENANT
+    
+    if [ "$SRDF_V3_VMAXA_NATIVEGUID" != "NONE" ]; then
+        storageport update $SRDF_V3_VMAXA_NATIVEGUID FC --addvarrays $V3_SRDF_VARRAY
+    fi
+    
+    if [ "$SRDF_V3_VMAXB_NATIVEGUID" != "NONE" ]; then
+        storageport update $SRDF_V3_VMAXB_NATIVEGUID FC --addvarrays $V3_SRDF_VARRAY
+    fi
+}
+
+srdf_v3_cos_setup()
+{
+     echo "*** SRDF V3 Virtual Pool setup ***" 
+    # Create the target first so it exists when we create the source vpool
+    cos show $COS_VMAXBLOCK_V3_SRDF_TARGET block &> /dev/null && return $?
+    cos create block $COS_VMAXBLOCK_V3_SRDF_TARGET		          \
+			 --description 'Target Virtual Pool for V3 SRDF Protection' true \
+			 --protocols FC 		          \
+			 --numpaths 1				  \
+			 --max_snapshots 10 			  \
+			 --provisionType 'Thin'	          \
+			 --neighborhoods $V3_SRDF_VARRAY                      \
+                         --multiVolumeConsistency                  \
+                         --system_type vmax			
+    
+    cos update block $COS_VMAXBLOCK_V3_SRDF_TARGET --storage ${SRDF_V3_VMAXB_NATIVEGUID}
+    cos update block $COS_VMAXBLOCK_V3_SRDF_TARGET --storage ${SRDF_V3_VMAXA_NATIVEGUID}
+    cos allow $COS_VMAXBLOCK_V3_SRDF_TARGET block $TENANT
+    
+    cos show ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active block &> /dev/null && return $?
+    cos create block ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active                 \
+			 --description 'Source Virtual Pool for Active SRDF Protection' true \
+			 --protocols FC 		        \
+			 --numpaths 1				\
+			 --max_snapshots 10			\
+	                 --provisionType 'Thin'	        \
+                         --system_type vmax                     \
+			 --neighborhoods $V3_SRDF_VARRAY                    \
+			 --srdf "${V3_SRDF_VARRAY}:${COS_VMAXBLOCK_V3_SRDF_TARGET}:ACTIVE"
+
+    cos update block ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active --storage ${SRDF_V3_VMAXA_NATIVEGUID}
+    cos update block ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active --storage ${SRDF_V3_VMAXB_NATIVEGUID}
+    cos allow ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active block $TENANT 
 }
 
 srdf_cos_matcher_test()
@@ -1326,6 +1370,21 @@ srdf_cos_change()
    sleep 60
    echo "Changing cos..."
    run volume change_cos $PROJECT/${srdfvolumecc} ${COS_VMAXBLOCK_SRDF_SOURCE}_sync
+   echo "Changed cos"
+   sleep 60
+   echo "Deleting volume"
+   run volume delete $PROJECT/${srdfvolumecc} --wait
+}
+
+srdf_v3_cos_change()
+{
+   # Create non-protected volume, then move it to a cos that has protection
+   srdfvolumecc="${SRDF_VOLUME}-coschange"
+   run volume create ${srdfvolumecc} $PROJECT $V3_SRDF_VARRAY $COS_VMAXBLOCK_V3_SRDF_TARGET 1GB
+   echo "Created volume, now sleeping..."
+   sleep 60
+   echo "Changing cos..."
+   run volume change_cos $PROJECT/${srdfvolumecc} ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active
    echo "Changed cos"
    sleep 60
    echo "Deleting volume"
@@ -1378,6 +1437,20 @@ srdf_basic_async_test()
    #run volume delete $PROJECT/${srdfvolume}3-2 --wait
 }
 
+srdf_basic_active_test()
+{
+   srdfvolume="${SRDF_VOLUME}_active"
+   run volume create ${srdfvolume}1 $SRDF_PROJECT $V3_SRDF_VARRAY ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active 1GB
+   run volume create ${srdfvolume}2 $SRDF_PROJECT $V3_SRDF_VARRAY ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active 1GB
+   sleep 60
+   run volume delete $SRDF_PROJECT/${srdfvolume}1 --wait
+   run volume delete $SRDF_PROJECT/${srdfvolume}2 --wait
+   run volume create ${srdfvolume}3 $SRDF_PROJECT $V3_SRDF_VARRAY ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active 1GB --consistencygroup $CONSISTENCY_GROUP_SRDF
+   run volume create ${srdfvolume}4 $SRDF_PROJECT $V3_SRDF_VARRAY ${COS_VMAXBLOCK_V3_SRDF_SOURCE}_active 1GB --consistencygroup $CONSISTENCY_GROUP_SRDF
+   run volume delete $SRDF_PROJECT/${srdfvolume}3 --wait
+   run volume delete $SRDF_PROJECT/${srdfvolume}4 --wait
+}
+
 srdf_tests()
 {
    echo 'Run SRDF tests'
@@ -1389,6 +1462,12 @@ srdf_tests()
    echo 'About to run basic SRDF sync test'
    sleep 60
    srdf_basic_sync_test
+   echo 'About to run basic SRDF active test'
+   sleep 60
+   srdf_basic_active_test
+   echo 'About to run V3 SRDF cos change test'
+   sleep 60
+   srdf_v3_cos_change
    echo 'About to run SRDF cos change test'
    sleep 60
    srdf_cos_change
@@ -7742,209 +7821,100 @@ start_vdc_services()
     done
 }
 
-#Usage: sanity <conf path> <vip> backuprestore backup-server-uri username password
-# E.g.: sanity conf/sanity.conf 137.69.169.21 backuprestore ftp://X.X.X.X/foo root root-password 
+#Usage: sanity <conf path> <vip> backuprestore
+# E.g.: sanity conf/sanity.conf 137.69.169.21 backuprestore
 backuprestore_setup()
 {
     echo "Setup backup restore environment begin"
-    login_nd_configure_smtp_nd_add_licenses
     vip=$BOURNE_IPADDR
 
-    echo "Enable root ssh permit and configure backup server"
+    echo "Enable root ssh permit"
     syssvc $CONFIG_FILE "$vip" set_prop system_permit_root_ssh yes
-
-    syssvc $CONFIG_FILE "$vip" set_prop backup_external_location_username "${BACKUP_SERVER_USERNAME}"
-    syssvc $CONFIG_FILE "$vip" set_prop backup_external_location_password "${BACKUP_SERVER_PASSWORD}"
-    syssvc $CONFIG_FILE "$vip" set_prop backup_external_location_url "${BACKUP_SERVER_URL}"
-
-    echo "Done url=${BACKUP_EXTERNAL_LOCATION_URL} username=${BACKUP_SERVER_USERNAME} password=${BACKUP_SERVER_PASSWORD}"
+    echo "Enable root ssh permit done"
 }
 
 backuprestore_tests()
 {
     backupname='sanity'
-    backupname2='abc'
     filepath='/tmp/sanity.zip'
-    remote_backup_file=""
 
-    backup_tests "${backupname}" "${backupname2}" "${filepath}"
+    backup_tests "${backupname}" "${filepath}"
     restore_tests "${filepath}"
 }
 
 backup_tests()
 {
-    local backupname=$1
-    local backupname2=$2
-    local filepath=$3
+    backupname=$1
+    filepath=$2
 
     echo "Creating backup(${backupname})"
     backup create "${backupname}"
-
-    if [ $? -ne 0 ]; then
-        echo "Create backup ${backupname} failed"
+    if [ $? == 0 ]; then
+        echo "Create backup successful"
+    else
+        echo "Create backup failed"
         exit 1
     fi
 
-    echo "Create backup ${backupname} successful"
-
-    echo "Creating another backup(${backupname2})"
-    backup create "${backupname2}"
-
-    if [ $? -ne 0 ]; then
-        echo "Create backup ${backupname2} failed"
+    echo "Creating backup(${backupname}-tmp)"
+    backup create "${backupname}-tmp"
+    if [ $? == 0 ]; then
+        echo "Create backup successful"
+    else
+        echo "Create backup failed"
         exit 1
     fi
 
-    echo "Create backup ${backupname2} successful"
-
-    echo "Listing local backup(${backupname})"
-    local found=$(backup list "${backupname}")
+    echo "Listing backup(${backupname})"
+    found=`backup list "${backupname}"`
     echo "found=$found"
-
-    if [ "$found"x != "${backupname}"x ]; then
+    if [ "$found"x == "${backupname}"x ]; then
+        echo "List backup successful"
+    else
         echo "List backup failed"
         exit 1
     fi
 
-    echo "List local backup ${backupname} successful"
-
-    echo "Uploading backup(${backupname}) to ${BACKUP_EXTERNAL_LOCATION_URL}"
-    backup upload "${backupname}"
-
-    if [ $? != 0 ]; then
-        echo "Upload backup ${backupname} failed"
-        exit 1
-    fi
-
-    echo "Wait for upload ${backupname} to complete"
-
-    for(( i=0; i<60; i++ )); do
-       status=$(backup query-upload "${backupname}")
-       echo "status=${status}"
-
-       if [[ "${status}" == "DONE" || "${status}" == "FAILED" ]] ; then
-           break;
-       fi
-
-       sleep 10s
-    done
-
-    echo "status=${status}"
-    if [[ "${status}" != "DONE" ]]; then
-        echo "upload backup ${backupname} failed"
-        exit 1
-    fi
-
-    echo "Listing external backup(${backupname} from ${BACKUP_EXTERNAL_LOCATION_URL})"
-
-    found=""
-    for(( i=0; i<60; i++ )); do
-       found=$(backup list-external "${backupname}")
-       echo "found=${found}"
-
-       if [[ "${found}" != "" ]]; then
-           break;
-       fi
-       sleep 10s
-    done
-
-    if [[ "${found}" == "" ]]; then
-       echo "Failed to find backup ${backupname} on ${BACKUP_EXTERNAL_LOCATION_URL}"
-       exit 1
-    fi
-
-    echo "Pull backup(${found} from ${BACKUP_EXTERNAL_LOCATION_URL})"
-    backup pull "${found}"
-
-    if [[ $? -ne 0 ]]; then
-        echo "pull backup failed"
-        exit 1
-    fi
-
-    echo "Start to query pull status"
-    local status=""
-
-    for (( i=0; i<60; i++ )); do
-       status=$(backup query-pull "${found}" "false")
-       echo "status=${status}"
-
-       if [[ "${status}" == "DOWNLOAD_SUCCESS" ]]; then
-           break;
-       fi
-
-       sleep 10s
-    done
-
-    if [[ "${status}" != "DOWNLOAD_SUCCESS" ]]; then
-       echo "Failed to pull backup ${found}"
-       exit 1
-    fi
-
-    remote_backup_file="${found}"
-
-    echo "Deleting backup(${backupname2})"
-    backup delete "${backupname2}"
-
-    if [[ $? -ne 0 ]]; then
+    echo "Deleting backup(${backupname}-tmp)"
+    backup delete "${backupname}-tmp"
+    if [ $? == 0 ]; then
+        echo "Delete backup successful"
+    else
         echo "Delete backup failed"
         exit 1
     fi
 
-    echo "Delete backup ${backupname2} successful"
-
-    echo "Listing backup(${backupname2})"
-
-    found=`backup list "${backupname2}"`
+    echo "Listing backup(${backupname}-tmp)"
+    found=`backup list "${backupname}-tmp"`
     echo "found=$found"
-
-    if [[ "$found"x == "${backupname2}"x ]]; then
+    if [ "$found"x == "${backupname}-tmp"x ]; then
         echo "Backup(${backupname}-tmp) should not exist"
         exit 1
     fi
 
     echo "Downloading backup(${backupname}) to ${filepath}"
-
     backup download "${backupname}" "${filepath}"
-
-    if [[ $? -ne 0 ||  ! -f ${filepath} ]]; then
+    if [[ $? == 0 && -f ${filepath} ]]; then
+        echo "Download backup successful"
+    else
         echo "Download backup failed"
         exit 1
     fi
 
-    echo "Download backup successful"
-
     echo "Deleting backup(${backupname})"
-
     backup delete "${backupname}"
-
-    if [[ $? -ne 0 ]]; then
+    if [ $? == 0 ]; then
+        echo "Delete backup successful"
+    else
         echo "Delete backup failed"
         exit 1
     fi
-
-    echo "Delete backup successful"
 }
 
 restore_tests()
 {
-    filepath="$1"
+    filepath=$1
     password=$SYSADMIN_PASSWORD
-
-    echo "Restore from pulled backup ${remote_backup_file} password=${password}"
-    backup restore "${remote_backup_file}" "false" "${password}"
-
-    echo "Wait for stable"
-    sleep 60s
-
-    for (( i=0; i<240; i++ )); do
-       security login $SYSADMIN $SYSADMIN_PASSWORD
-
-       if [[ $? -eq 0 ]]; then
-            break;
-       fi
-       echo "login failed retry later"
-       sleep 10s
-    done
 
     echo "Uploading backup file ${filepath} to $BOURNE_IPADDR"
     SCP $BOURNE_IPADDR ${filepath} ${filepath}
@@ -7952,7 +7922,7 @@ restore_tests()
     echo "Restoring backup file ${filepath} on $BOURNE_IPADDR"    
     result=`SSH $BOURNE_IPADDR "echo -e 'yes\n$password' | /opt/storageos/bin/restore '${filepath}'" | grep 'Restore'`
     echo "$result"
-    if [[ "$result"x != "Restore successful!"x ]]; then
+    if [ "$result"x != "Restore successful!"x ]; then
         echo "Please check /opt/storageos/logs/bkutils.log for details"
         exit 1
     fi
@@ -8128,7 +8098,7 @@ fail(){
 
 trap _failure ERR INT
 set -E
-if [ "$3" != "vdc" ] && [ "$3" != "dr" ] && [ "$3" != "backuprestore" ]; then
+if [ "$3" != "vdc" ] && [ "$3" != "dr" ]; then
     common_setup	
 fi
 
