adding support for vplex with simulator

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -1873,7 +1873,7 @@ rp_targets()
 # All varrays for RP+VPLEX targets
 rpvplex_targets()
 {
-    run cos create block rpvplex_targets$1 true \
+    run cos create block rpvplex_targets$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX-Targets' \
         --protocols FC \
         --numpaths 2 \
@@ -1886,7 +1886,7 @@ rpvplex_targets()
 # All varrays for HA
 rpvplex_ha()
 {
-    run cos create block rpvplex_ha$1 true \
+    run cos create block rpvplex_ha$1 $POOLS_AUTO_MATCH \
         --description 'HA' \
         --protocols FC \
         --numpaths 2 \
@@ -1898,7 +1898,7 @@ rpvplex_ha()
 # Regular vpool used as base for change vpool tests
 rp_regular()
 {
-    run cos create block rp_regular$1 true \
+    run cos create block rp_regular$1 $POOLS_AUTO_MATCH \
         --description 'Regular-vpool-used-as-base-for-change-vpool-tests' \
         --protocols FC \
         --numpaths 2 \
@@ -1910,7 +1910,7 @@ rp_regular()
 # Regular VPLEX local vpool used as base for change vpool tests
 rpvplex_local_regular()
 {
-    run cos create block rpvplex_local_regular$1 true \
+    run cos create block rpvplex_local_regular$1 $POOLS_AUTO_MATCH \
         --description 'Regular-VPLEX-local-vpool-used-as-base-for-change-vpool-tests' \
         --protocols FC \
         --numpaths 2 \
@@ -1922,7 +1922,7 @@ rpvplex_local_regular()
 # Regular VPLEX dist vpool used as base for change vpool tests
 rpvplex_dist_regular()
 {
-    run cos create block rpvplex_dist_regular$1 true \
+    run cos create block rpvplex_dist_regular$1  $POOLS_AUTO_MATCH \
         --description 'Regular-VPLEX-dist-vpool-used-as-base-for-change-vpool-tests' \
         --protocols FC \
         --numpaths 2 \
@@ -1946,6 +1946,19 @@ rp_cdp()
         --protectionCoS $RECOVERPOINT_VARRAY1':rp_targets'$1':min' \
         --max_snapshots 10 \
         --rp_copy_mode ASYNCHRONOUS \
+        --rp_rpo_value 5 \
+        --rp_rpo_type MINUTES
+
+    run cos create block rp_cdp$1-sync $POOLS_AUTO_MATCH \
+        --description 'RP-Source-CDP-with-Sync'  \
+        --protocols FC \
+        --numpaths 2 \
+        --provisionType 'Thin' \
+        --neighborhoods $RECOVERPOINT_VARRAY1 \
+        --multiVolumeConsistency \
+        --protectionCoS $RECOVERPOINT_VARRAY1':rp_targets'$1':min' \
+        --max_snapshots 10 \
+        --rp_copy_mode SYNCHRONOUS \
         --rp_rpo_value 5 \
         --rp_rpo_type MINUTES
 }
@@ -1987,7 +2000,7 @@ rp_clr()
 # RP+VPLEX CDP
 rpvplex_cdp()
 {
-    run cos create block rpvplex_cdp$1 true \
+    run cos create block rpvplex_cdp$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX-Source-CDP'  \
         --protocols FC \
         --numpaths 2 \
@@ -2004,7 +2017,7 @@ rpvplex_cdp()
 # RP+VPLEX CRR
 rpvplex_crr()
 {
-    run cos create block rpvplex_crr$1 true \
+    run cos create block rpvplex_crr$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX-Source-CRR'  \
         --protocols FC \
         --numpaths 2 \
@@ -2023,7 +2036,7 @@ rpvplex_crr()
 # RP+VPLEX CLR
 rpvplex_clr()
 {
-    run cos create block rpvplex_clr$1 true \
+    run cos create block rpvplex_clr$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX-Source-CLR'  \
         --protocols FC \
         --numpaths 2 \
@@ -2042,7 +2055,7 @@ rpvplex_clr()
 # MetroPoint CDP
 mp_cdp()
 {
-    run cos create block mp_cdp$1 true \
+    run cos create block mp_cdp$1 $POOLS_AUTO_MATCH \
         --description 'MetroPoint-Source-CDP'  \
         --protocols FC \
         --numpaths 2 \
@@ -2063,7 +2076,7 @@ mp_cdp()
 # MetroPoint CRR
 mp_crr()
 {
-    run cos create block mp_crr$1 true \
+    run cos create block mp_crr$1 $POOLS_AUTO_MATCH \
         --description 'MetroPoint-Source-CRR'  \
         --protocols FC \
         --numpaths 2 \
@@ -2084,7 +2097,7 @@ mp_crr()
 # MetroPoint CLR
 mp_clr()
 {
-    run cos create block mp_clr$1 true \
+    run cos create block mp_clr$1 $POOLS_AUTO_MATCH \
         --description 'MetroPoint-CLR'  \
         --protocols FC \
         --numpaths 2 \
@@ -2105,7 +2118,7 @@ mp_clr()
 # RP - NO PROTECTION
 rp_noprotection()
 {
-    cos create block rp_noprotection$1 true \
+    cos create block rp_noprotection$1 $POOLS_AUTO_MATCH \
         --description 'RP - NO PROTECTION'  \
         --protocols FC \
         --numpaths 2 \
@@ -2117,7 +2130,7 @@ rp_noprotection()
 # RP+VPLEX LOCAL - NO PROTECTION
 rpvplexlocal_noprotection()
 {
-    cos create block rpvplexlocal_noprotection$1 true \
+    cos create block rpvplexlocal_noprotection$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX LOCAL - NO PROTECTION'  \
         --protocols FC \
         --numpaths 2 \
@@ -2130,7 +2143,7 @@ rpvplexlocal_noprotection()
 # RP+VPLEX DIST - NO PROTECTION
 rpvplexdist_noprotection()
 {
-    cos create block rpvplexdist_noprotection$1 true \
+    cos create block rpvplexdist_noprotection$1 $POOLS_AUTO_MATCH \
         --description 'RP+VPLEX DIST - NO PROTECTION'  \
         --protocols FC \
         --numpaths 2 \
@@ -2269,27 +2282,29 @@ rp_port_setup()
     # Override port to varray assigments for VPLEX clusters to prevent port mixing in clusters
     # Source Site
     # Cluster 1
-    if [ "$RECOVERPOINT_VPLEX_A" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_A_GUID" != "NONE" ]; then
-        storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-1-1-A --addvarrays $RECOVERPOINT_VARRAY1
-        storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-1-1-B --addvarrays $RECOVERPOINT_VARRAY1
-    fi
-    # Cluster 2
-    if [ "$RECOVERPOINT_VPLEX_A" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_B_GUID" != "NONE" ]; then
-        storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-2-1-A --addvarrays $RECOVERPOINT_VARRAY2
-        storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-2-1-B --addvarrays $RECOVERPOINT_VARRAY2
-    fi
+    if [ "${RPVPLEX_TESTS}" = "1" ]; then
+	if [ "$RECOVERPOINT_VPLEX_A" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_A_GUID" != "NONE" ]; then
+	    storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-1-1-A --addvarrays $RECOVERPOINT_VARRAY1
+	    storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-1-1-B --addvarrays $RECOVERPOINT_VARRAY1
+	fi
+        # Cluster 2
+	if [ "$RECOVERPOINT_VPLEX_A" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_B_GUID" != "NONE" ]; then
+	    storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-2-1-A --addvarrays $RECOVERPOINT_VARRAY2
+	    storageport update $RECOVERPOINT_VPLEX_A_GUID FC --group director-2-1-B --addvarrays $RECOVERPOINT_VARRAY2
+	fi
 
-    # Target Site
-    # Cluster 1
-    if [ "$RECOVERPOINT_VPLEX_B" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_C_GUID" != "NONE" ]; then
-        storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-1-1-A --addvarrays $RECOVERPOINT_VARRAY3
-        storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-1-1-B --addvarrays $RECOVERPOINT_VARRAY3
-    fi
+        # Target Site
+        # Cluster 1
+	if [ "$RECOVERPOINT_VPLEX_B" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_C_GUID" != "NONE" ]; then
+	    storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-1-1-A --addvarrays $RECOVERPOINT_VARRAY3
+	    storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-1-1-B --addvarrays $RECOVERPOINT_VARRAY3
+	fi
 
-    # Cluster 2
-    if [ "$RECOVERPOINT_VPLEX_B" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_D_GUID" != "NONE" ]; then
-        storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-2-1-A --addvarrays $RECOVERPOINT_VARRAY4
-        storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-2-1-B --addvarrays $RECOVERPOINT_VARRAY4
+        # Cluster 2
+	if [ "$RECOVERPOINT_VPLEX_B" != "NONE" ] && [ "$RECOVERPOINT_STORAGE_ARRAY_D_GUID" != "NONE" ]; then
+	    storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-2-1-A --addvarrays $RECOVERPOINT_VARRAY4
+	    storageport update $RECOVERPOINT_VPLEX_B_GUID FC --group director-2-1-B --addvarrays $RECOVERPOINT_VARRAY4
+	fi
     fi
 }
 
@@ -2443,7 +2458,7 @@ recoverpoint_ingest_setup()
     if [ ${RP_CRR} = "1" -o ${RP_CLR} = "1" ]; then
 	INGEST_NATIVEGUID2=$RECOVERPOINT_STORAGE_ARRAY_C_GUID
 	if [ "$RP_QUICK_PARAM" == "quick" ]; then
-	    INGEST_NATIVEGUID2=$VMAX2_SIMULATOR_NATIVEGUID
+	    INGEST_NATIVEGUID2=$VMAX3_SIMULATOR_NATIVEGUID
 	fi
     fi	
 
@@ -2503,6 +2518,9 @@ recoverpoint_ingest_test()
 
     rpsnap=rpsnap_for_validation-${RP_MODIFIED_HOSTNAME}-${RANDOM}
     if [ "${vpool}" = "rp_cdp" ]; then
+	# Make sure it fails against a different sync policy than what's on the RPA
+	fail unmanagedvolume ingest_unexport ${RECOVERPOINT_VARRAY1} rp_cdp-sync $PROJECT --volspec "${RECOVERPOINT_INGEST_VOL1_SRC}"
+
 	run unmanagedvolume ingest_unexport ${RECOVERPOINT_VARRAY1} rp_cdp $PROJECT --volspec "${RECOVERPOINT_INGEST_VOL1_SRC}"
 	run unmanagedvolume ingest_unexport ${RECOVERPOINT_VARRAY1} rp_targets $PROJECT --volspec "${RECOVERPOINT_INGEST_VOL1_TGT}"
 	run unmanagedvolume ingest_unexport ${RECOVERPOINT_VARRAY1} rp_targets $PROJECT --volspec "${RECOVERPOINT_INGEST_VOL1_TGT_JRNL}"
@@ -2859,62 +2877,61 @@ recoverpoint_simulator_setup()
     project_setup
     rp_varray_setup
 
-
     syssvc $CONFIG_FILE localhost set_prop controller_discovery_refresh_interval 5
-    #    elif [ "$PARAM" = "simulator" ]; then
 
     # Simulators being used
-     run smisprovider create $PROVIDER_SIMULATOR $RP_PROVIDER_SIMULATOR_IP $RP_VMAX_SMIS_SIM_PORT $SMIS_USER "$SMIS_PASSWD" false
-     run networksystem create $FABRIC_SIMULATOR  mds --devip $SIMULATOR_CISCO_MDS_IP --devport 22 --username $RP_FABRIC_SIM_USER --password $RP_FABRIC_SIM_PW
-     storagedevice discover_all
-     
-     run transportzone assign VSAN_11 ${RECOVERPOINT_VARRAY1}
-     run transportzone assign VSAN_13 ${RECOVERPOINT_VARRAY3}
+    run smisprovider create $PROVIDER_SIMULATOR $RP_PROVIDER_SIMULATOR_IP $RP_VMAX_SMIS_SIM_PORT $SMIS_USER "$SMIS_PASSWD" false
+    run networksystem create $FABRIC_SIMULATOR  mds --devip $SIMULATOR_CISCO_MDS_IP --devport 22 --username $RP_FABRIC_SIM_USER --password $RP_FABRIC_SIM_PW
+    
+    if [ "${RPVPLEX_TESTS}" = "1" ]; then
+        # VPLEX
+        VPLEX_DEV_NAME=$VPLEX_SIMULATOR
+        VPLEX_IP=$SIMULATOR_IP
+        storageprovider show $VPLEX_DEV_NAME &> /dev/null && return $?
+        run storageprovider create $VPLEX_DEV_NAME $VPLEX_IP 443 $VPLEX_USER "$VPLEX_PASSWD" vplex
+    fi
 
-     POOLS_AUTO_MATCH=false
+    run storagedevice discover_all
+    run transportzone assign VSAN_11 ${RECOVERPOINT_VARRAY1}
+    run transportzone assign VSAN_13 ${RECOVERPOINT_VARRAY3}
 
-     RECOVERPOINT=$RP_SIMULATOR
-     RECOVERPOINT_IP=$RP_SIMULATOR_IP
-     rp_protection_system_setup
+    POOLS_AUTO_MATCH=false
 
-     run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_1rp1 --addvarrays $RECOVERPOINT_VARRAY1
-     run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_2rp1 --addvarrays $RECOVERPOINT_VARRAY2
-     run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_3rp1 --addvarrays $RECOVERPOINT_VARRAY3
+    RECOVERPOINT=$RP_SIMULATOR
+    RECOVERPOINT_IP=$RP_SIMULATOR_IP
+    rp_protection_system_setup
 
-     run storagepool update $VMAX1_SIMULATOR_NATIVEGUID --nhadd $RECOVERPOINT_VARRAY1 --type block
-     run storagepool update $VMAX2_SIMULATOR_NATIVEGUID --nhadd $RECOVERPOINT_VARRAY3 --type block
+    # Make sure all of the pools are updated and matched
+    run storagedevice discover_all
 
+    run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_1rp1 --addvarrays $RECOVERPOINT_VARRAY1
+    run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_2rp1 --addvarrays $RECOVERPOINT_VARRAY2
+    run protectionsystem update --ip ${remote_ip} --name $RECOVERPOINT --cluster site_3rp1 --addvarrays $RECOVERPOINT_VARRAY3
 
-     # Simulator adjustments to cos (shouldn't be needed but RP simulator only sees a subset of what's on the network)
-     rp_targets
-     run cos update block rp_targets --storage $VMAX1_SIMULATOR_NATIVEGUID
-     run cos update block rp_targets --storage $VMAX2_SIMULATOR_NATIVEGUID
-     rp_cdp
-     run cos update block rp_cdp --storage $VMAX1_SIMULATOR_NATIVEGUID
-     rp_crr
-     run cos update block rp_crr --storage $VMAX1_SIMULATOR_NATIVEGUID
-     run cos update block rp_crr --storage $VMAX2_SIMULATOR_NATIVEGUID
-     rp_clr
-     run cos update block rp_clr --storage $VMAX1_SIMULATOR_NATIVEGUID
-     run cos update block rp_clr --storage $VMAX2_SIMULATOR_NATIVEGUID
+    run storagepool update $VMAX1_SIMULATOR_NATIVEGUID --nhadd $RECOVERPOINT_VARRAY1 --type block
+    run storagepool update $VMAX3_SIMULATOR_NATIVEGUID --nhadd $RECOVERPOINT_VARRAY3 --type block
 
-#
-#        # VPLEX
-#        VPLEX_DEV_NAME=$VPLEX_SIMULATOR
-#        VPLEX_IP=$SIMULATOR_IP
-#        storageprovider show $VPLEX_DEV_NAME &> /dev/null && return $?
-#        run storageprovider create $VPLEX_DEV_NAME $VPLEX_IP 443 $VPLEX_USER "$VPLEX_PASSWD" vplex
-#        run storagedevice discover_all
-#        transportzone assign ${SIMULATOR_VSAN_11} $NH
-#
-#        # simulators being used
+    # Simulator adjustments to cos (shouldn't be needed but RP simulator only sees a subset of what's on the network)
+    rp_vpool_setup
 
-#
-#        # simulators being used
-#        echo 'Using simulators in recoverpoint_common_setup'
-#        transportzone assign ${SIMULATOR_VSAN_11} $NH
-#        RP_NATIVE_GUID=$VMAX1_SIMULATOR_NATIVEGUID
-#    fi
+    run cos update block rp_targets --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rp_targets --storage $VMAX3_SIMULATOR_NATIVEGUID
+    run cos update block rp_cdp --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rp_cdp-sync --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rp_crr --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rp_crr --storage $VMAX3_SIMULATOR_NATIVEGUID
+    run cos update block rp_clr --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rp_clr --storage $VMAX3_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_targets --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_targets --storage $VMAX2_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_targets --storage $VMAX3_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_ha --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_ha --storage $VMAX2_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_ha --storage $VMAX3_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_cdp --storage $VMAX1_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_cdp --storage $VMAX2_SIMULATOR_NATIVEGUID
+    run cos update block rpvplex_cdp --storage $VMAX3_SIMULATOR_NATIVEGUID
+
 }
 
 
