COP-17668: sleep 30s before resume data replication.

diff --git a/tools/tests/sanity b/tools/tests/sanity
--- a/tools/tests/sanity
+++ b/tools/tests/sanity
@@ -6330,13 +6330,13 @@ dr_basic_tests()
     echo "---PAUSE SITE $standby_site---"
     BOURNE_IPADDR=$DR_SITE_A_IP
     security login $LOCAL_LDAP_GROUPUSER_USERNAME $LOCAL_LDAP_GROUPUSER_PASSWORD
-    dr pause $standby_site
+    dr pause $standby_site || { echo "pause dr standby site failed."; exit 1; }
 
-    echo "---WAIT FOR $primary_site TO STABILIZE---"
-    vdc waitforstablestate 10 600
+    echo "---WAIT 30s FOR $primary_site TO STABILIZE---"
+    sleep 30
 
     echo "---RESUME SITE $standby_site---"
-    dr resume $standby_site
+    dr resume $standby_site || { echo "resume dr standby site failed."; exit 1; }
 
     echo "---WAIT FOR SYNC $standby_site---"
     dr waitforstate $standby_site STANDBY_SYNCED 30 600
