COP-25998: add a hidden parameter '-f' for restore script

diff --git a/internalLibraries/backup/src/scripts/restore b/internalLibraries/backup/src/scripts/restore
--- a/internalLibraries/backup/src/scripts/restore
+++ b/internalLibraries/backup/src/scripts/restore
@@ -44,7 +44,7 @@ upload_backup() {
         return
     fi
 
-    echo "Uploading backup files to all nodes ... "
+    echo -n "Uploading backup files to all nodes ... "
     create_restore_folder
     extract_backup_files
     copy_to_other_nodes
@@ -87,21 +87,45 @@ validate_backup_files() {
         echo -e "\nCan't find valid backup files under $RESTORE_DIR, exiting.."
         exit 2
     elif [ ${fileNodeCount} -lt $[ $BACKUP_NODE_COUNT / 2 + 1 ] ]; then
-        echo -e "\nThis backupset is invalid, exiting.."
-        exit 2
+        echo -e -n "\nThis backupset is invalid, "
+        if [ ${FORCE} == true ]; then
+            echo "force restore may still be failed."
+            user_confirm "Are you sure you want to continue?"
+        else
+            echo "exiting.."
+            exit 2
+        fi
     elif [ ${fileNodeCount} -lt $BACKUP_NODE_COUNT ]; then
         echo -n "WARNING: This is an incomplete backupset.."
         if [ $NODE_COUNT != $BACKUP_NODE_COUNT ]; then
-            echo -e "\nCluster nodes count can't change in restoring with incomplete backupset, exiting.."
-            exit 2
+            echo -e -n "\nCluster nodes count can't change in restoring with incomplete backupset, "
+            if [ ${FORCE} == true ]; then
+                echo "force restore may still be failed."
+                user_confirm "Are you sure you want to continue?"
+            else
+                echo "exiting.."
+                exit 2
+            fi
         fi
     elif [ ${fileNodeCount} -eq $BACKUP_NODE_COUNT ]; then
         if [ $NODE_COUNT -lt $[ $BACKUP_NODE_COUNT / 2 + 1 ] ]; then
-            echo -e "\nNodes count of cluster to be restored should not be less than quorum nodes count of cluster taken backup, exiting.."
-            exit 2
+            echo -e -n "\nNodes count of cluster to be restored should not be less than quorum nodes count of cluster taken backup, "
+            if [ ${FORCE} == true ]; then
+                echo "force restore may still be failed."
+                user_confirm "Are you sure you want to continue?"
+            else
+                echo "exiting.."
+                exit 2
+            fi
         elif [ $BACKUP_NODE_COUNT -lt $[ $NODE_COUNT / 2 + 1 ] ]; then
-            echo -e "\nNodes count of cluster taken backup should not be less than quorum nodes count of cluster to be restored, exiting.."
-            exit 2
+            echo -e -n "\nNodes count of cluster taken backup should not be less than quorum nodes count of cluster to be restored, "
+            if [ ${FORCE} == true ]; then
+                echo "force restore may still be failed."
+                user_confirm "Are you sure you want to continue?"
+            else
+                echo "exiting.."
+                exit 2
+            fi
         elif [ $NODE_COUNT != $BACKUP_NODE_COUNT ]; then
             if [[ ${IS_CONNECTED_VDC} == true ]]; then
                 echo -e "\nCluster nodes count can't change when backup was taken in geo system, exiting.."
@@ -170,14 +194,17 @@ check_standby() {
     fi
 }
 
-if [ $# -ne 1 ]; then
+if [ $# -eq 1 ]; then
+    if [ "$1" == "--help" -o "$1" == "-h" -o "$1" == "-help" ]; then
+        usage
+        exit 0
+    fi
+    FORCE=false
+elif [ $# -eq 2 ] && [ "$2" == "-f" ]; then
+    FORCE=true
+else
     usage
     exit 2
-fi
-
-if [ "$1" == "--help" -o "$1" == "-h" -o "$1" == "-help" ]; then
-    usage
-    exit 0
 fi
 
 RESTORE_DIR="/data/restore-`date +%s`"
