Adding deb target

diff --git a/packaging/Makefile b/packaging/Makefile
--- a/packaging/Makefile
+++ b/packaging/Makefile
@@ -979,6 +979,22 @@ ifeq ($(BUILD_TYPE),emc)
 	$(ATSIGN)$(MKDIR) $(INSTALL_PREFIX)/opt/connectemc
 	$(ATSIGN)$(CP) -a $(BUILD_BASE)/connectemc             $(INSTALL_PREFIX)/opt/
 endif
+ifeq ($(OS_DISTRO),trusty-tahr)
+	$(ATECHO) mv -f trusty-tahr
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/trusty-tahr/init $(INSTALL_PREFIX)/etc/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/trusty-tahr/oss/systool  $(INSTALL_PREFIX)/etc/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/trusty-tahr/oss/storageos/boot-ovfenv  $(INSTALL_PREFIX)/etc/storageos/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/trusty-tahr/storageos/storageos $(INSTALL_PREFIX)/etc/storageos/
+	$(ATSIGN)$(RM) -r $(INSTALL_PREFIX)/etc/trusty-tahr
+endif
+ifeq ($(OS_DISTRO),xenial-xerus)
+	$(ATECHO) mv -f xenial-xerus
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/xenial-xerus/init $(INSTALL_PREFIX)/etc/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/xenial-xerus/oss/systool  $(INSTALL_PREFIX)/etc/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/xenial-xerus/oss/storageos/boot-ovfenv  $(INSTALL_PREFIX)/etc/storageos/
+	$(ATSIGN)$(MV) -f $(INSTALL_PREFIX)/etc/xenial-xerus/storageos/storageos $(INSTALL_PREFIX)/etc/storageos/
+	$(ATSIGN)$(RM) -r $(INSTALL_PREFIX)/etc/xenial-xerus
+endif
 	$(ATSIGN)$(RM) -r $(INSTALL_PREFIX)$(PRODUCT_PREFIX)
 	$(ATSIGN)$(MKDIR) $(INSTALL_PREFIX)$(PRODUCT_PREFIX)
 	$(ATECHO) cp -a bin lib conf cli pylib
@@ -1033,6 +1049,59 @@ clean:: clean-rpm
 clobber::
 	$(ATSIGN)$(RM) -r $(RPMBUILD_RPMS_DIR)
 
+# DEB section
+#
+.PHONY: deb clean-deb 
+
+deb: $(DEBBUILD_DEB_FILE)
+
+$(DEBBUILD_DEB_FILE): $(DEBBUILD_CONTROL_DEPS)
+	@$(ECHO) "Building storageos Debian package (release $(PRODUCT_VERSION).$(PRODUCT_RELEASE))"
+	$(ATSIGN)$(RM)    $(@)
+	$(ATSIGN)$(RM) -r       $(DEBBUILD_BUILDDIR) 
+	$(ATSIGN)$(MKDIR) $(@D) $(DEBBUILD_BUILDDIR) $(DEBBUILD_TARGET_CONTROLDIR)
+	@$(ECHO) "Installing source files in $(DEBBUILD_BUILDROOT)..."
+	$(ATSIGN)$(MAKE) _install INSTALL_PREFIX="$(DEBBUILD_BUILDROOT)"
+	@$(ECHO) "Removing non debian directories and files..."
+	$(ATSIGN)$(RM) -r $(DEBBUILD_BUILDROOT)/etc/boot-ovfenv.conf $(DEBBUILD_BUILDROOT)/etc/nginx.conf
+	$(ATSIGN)$(RM) -r $(DEBBUILD_BUILDROOT)/etc/systemd
+	$(ATSIGN)$(RM) -r $(DEBBUILD_BUILDROOT)/etc/sysconfig/SuSE*
+	$(ATSIGN)for svc in api auth controller coordinator db geo geodb portal sa sys; do \
+		sed -e "s,@svcname@,$$svc,g" $(DEBBUILD_BUILDROOT)/etc/init/storageos-template.conf > $(DEBBUILD_BUILDROOT)/etc/init/storageos-$$svc.conf; \
+	done
+	$(ATSIGN)$(RM) -r $(DEBBUILD_BUILDROOT)/etc/init/storageos-template.conf
+	@$(ECHO) "Creating $(DEBBUILD_TARGET_CONTROL_FILE).."
+	$(ATSIGN)$(MAKE) $(DEBBUILD_TARGET_CONTROL_FILE)
+	@$(ECHO) "Copying $(DEBBUILD_PRERM_FILE),$(DEBBUILD_POSTRM_FILE),$(DEBBUILD_POSTINST_FILE) files.."
+	$(ATSIGN)$(CP) 	$(DEBBUILD_SRC_CONTROLDIR)/$(DEBBUILD_PRERM_FILE) $(DEBBUILD_TARGET_CONTROLDIR)/
+	$(ATSIGN)$(CP) 	$(DEBBUILD_SRC_CONTROLDIR)/$(DEBBUILD_POSTRM_FILE) $(DEBBUILD_TARGET_CONTROLDIR)/
+	$(ATSIGN)$(CP) 	$(DEBBUILD_SRC_CONTROLDIR)/$(DEBBUILD_POSTINST_FILE) $(DEBBUILD_TARGET_CONTROLDIR)/
+	@$(ECHO) "Changing scripts with right bash, java home etc. env variables .."
+	$(ATSIGN)for dir in "opt/storageos/bin" "etc/genconfig.d" "etc/storageos/"; do \
+		sed -i 's/#!\/bin\/sh/#!\/bin\/bash/g' $(DEBBUILD_BUILDROOT)/$$dir/*; \
+		sed -i "s/^export JAVA_HOME=.*$$/export JAVA_HOME=\/usr\/lib\/jvm\/java-8-openjdk-amd64\/jre/g" $(DEBBUILD_BUILDROOT)/$$dir/*; \
+		sed -i "s/\/usr\/bin\/sed/\/bin\/sed/g" $(DEBBUILD_BUILDROOT)/$$dir/*; \
+	done
+	@$(ECHO) "Creating $(DEBBUILD_TARGET_CONTROLDIR)/$(DEBBUILD_MD5_FILE) file.."
+	$(ATSIGN)$(FIND) $(DEBBUILD_BUILDDIR) -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '"'"$(DEBBUILD_BUILDDIR)/"'%P" ' | xargs md5sum | $(SED) -e "s#$(DEBBUILD_BUILDROOT)/##g" > $(DEBBUILD_TARGET_CONTROLDIR)/$(DEBBUILD_MD5_FILE)
+	@$(ECHO) "Building Debian Packaging using $(DEBBUILD) -b $(DEBBUILD_BUILDROOT) $(DEBBUILD_FLAGS).."
+	$(ATSIGN)dpkg-deb -b $(DEBBUILD_BUILDROOT) $(DEBBUILD_FLAGS) $(TEEOUT) $(DEBBUILD_LOG)
+	$(ATSIGN)$(MV) $(DEBBUILD_BUILDDIR)/$(notdir $@) $@
+	@[ -f "$(@)" ] || { echo "debbuild failed!"; exit 1 ; }
+	@echo "***"
+	@echo "*** $(DEBBUILD_NAME) DEB:"
+	@echo "***    $(@)"
+	@echo "***"
+
+$(DEBBUILD_TARGET_CONTROL_FILE): $(DEBBUILD_SRC_CONTROLDIR)/$(DEBBUILD_MD5_FILE)
+	$(ATSIGN)$(SED) -e "s#<<package>>#$(DEBBUILD_NAME)#g" \
+               -e "s#<<version>>#$(PRODUCT_VERSION).$(PRODUCT_RELEASE)-$(DEB_REVISION)#g" \
+               -e "s#<<architecture>>#$(DEBBUILD_DEB_ARCH_FORMATTED)#g" \
+               -e "s#<<description>>#$(DEBBUILD_NAME)-$(PRODUCT_VERSION).$(PRODUCT_RELEASE)-$(DEB_REVISION)#g" \
+	       $(DEBBUILD_SRC_CONTROLDIR)/$(DEBBUILD_CONTROL_FILE) > $(DEBBUILD_TARGET_CONTROL_FILE)
+
+deb-clean:
+	$(ATSIGN)$(RM) -r $(DEBBUILD_DEB_FILE) $(DEBBUILD_BUILDDIR)
 
 # Handy hack
 #
@@ -1048,3 +1117,4 @@ clobber::
 
 # END $Rev: XXX $
 
+print-%  : ; @echo $* = $($*)
